spring:
  application:
    name: CheapCheese

  data:
    mongodb:
      authentication-database: admin
      database: CheapCheese
      username: rootuser
      password: rootpass
      port: 27017
      host: localhost

  security:
    user:
      name: admin
      password: admin

cheapcheese:
  app:
    jwtCookieName: cheapCheese
    jwtSecret: PNijKumE84KfExpQQQcDfzKRKdqR7mXro0wPzwYBOtY=
    jwtExpirationMs: 120000